# tpl2x package Makefile

SHELL       = /bin/bash
CFG         = .env
GO         ?= go
SOURCES    ?= *.go */*.go

CODECOV_KEY =

define CONFIG_DEF
# ------------------------------------------------------------------------------
# tpl2x config file, generated by make $(CFG)

# codecov.io API key
CODECOV_KEY=$(CODECOV_KEY)
endef
export CONFIG_DEF

# ------------------------------------------------------------------------------

-include $(CFG)
export

# ------------------------------------------------------------------------------

## run tests and fill coverage.out
cov: coverage.out

# internal target
coverage.out: $(SOURCES) gin-tpl2x/coverage.out
	$(GO) test -race -coverprofile=$@ -covermode=atomic ./...
	grep -v "mode: atomic" gin-tpl2x/$@ >> $@

# internal target
gin-tpl2x/coverage.out: gin-tpl2x/*.go
	pushd gin-tpl2x ; \
	$(GO) test -race -coverprofile=$@ -covermode=atomic ; \
	popd


## make coverage.out and send it to codecov.io
cov-pub: cov
	bash <(curl -s https://codecov.io/bash) -t $(CODECOV_KEY)

## open browser with coverage report
cov-html: cov
	$(GO) tool cover -html=coverage.out

# ------------------------------------------------------------------------------

## create initial config
$(CFG):
	@[ -f $@ ] || { echo "$$CONFIG_DEF" > $@ ; echo "Warning: Created default $@" ; }

# ------------------------------------------------------------------------------

## List Makefile targets
help:
	@grep -A 1 "^##" Makefile | less

##
## Press 'q' for exit
##
